### ISSUE TITLE
Is it compatible with Rails 4 ?

### ISSUE THREAD

**Issue by peyloride** [developergagan/likeit#1]
Hi, 

I was tryin likeit gem to my rails 4 app. But when i try "rails g likeit" i'm facing with errors;

```
rails g likeit
/home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.4/lib/active_record/dynamic_matchers.rb:26:in `method_missing': undefined local variable or method `acts_as_voter' for User (call 'User.connection' to establish a connection):Class (NameError)
from /home/peyloride/RailsProjects/ecokat/app/models/user.rb:7:in `<class:User>'
from /home/peyloride/RailsProjects/ecokat/app/models/user.rb:1:in `<top (required)>'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:457:in `load'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:457:in `block in load_file'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:647:in `new_constants_in'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:456:in `load_file'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:354:in `require_or_load'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:494:in `load_missing_constant'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:184:in `const_missing'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:261:in `const_get'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:261:in `block in constantize'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:259:in `each'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:259:in `inject'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:259:in `constantize'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:566:in `get'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:597:in `constantize'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.4.1/lib/devise.rb:302:in `get'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.4.1/lib/devise/mapping.rb:80:in `to'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.4.1/lib/devise/mapping.rb:75:in `modules'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.4.1/lib/devise/mapping.rb:92:in `routes'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.4.1/lib/devise/mapping.rb:159:in `default_used_route'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.4.1/lib/devise/mapping.rb:69:in `initialize'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.4.1/lib/devise.rb:336:in `new'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.4.1/lib/devise.rb:336:in `add_mapping'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.4.1/lib/devise/rails/routes.rb:224:in `block in devise_for'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.4.1/lib/devise/rails/routes.rb:223:in `each'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.4.1/lib/devise/rails/routes.rb:223:in `devise_for'
from /home/peyloride/RailsProjects/ecokat/config/routes.rb:3:in `block in <top (required)>'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:434:in `instance_exec'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:434:in `eval_block'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:412:in `draw'
from /home/peyloride/RailsProjects/ecokat/config/routes.rb:1:in `<top (required)>'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:40:in `each'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:40:in `load_paths'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:16:in `reload!'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:26:in `block in updater'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/file_update_checker.rb:75:in `call'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/file_update_checker.rb:75:in `execute'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:27:in `updater'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `call'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
from /home/peyloride/RailsProjects/ecokat/config/environment.rb:5:in `<top (required)>'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.5.0/lib/spring/application.rb:92:in `preload'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.5.0/lib/spring/application.rb:143:in `serve'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.5.0/lib/spring/application.rb:131:in `block in run'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.5.0/lib/spring/application.rb:125:in `loop'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.5.0/lib/spring/application.rb:125:in `run'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.5.0/lib/spring/application/boot.rb:18:in `<top (required)>'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from /home/peyloride/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from -e:1:in `<main>'
```

Is there any fix for that?

**Comment by peyloride** [comment]
Totally my fault. Gem is just working fine with rails 4. Thanks for your work!
